spring.application.name=RideBooking

#DB
spring.datasource.url = jdbc:postgresql://localhost:5432/RideBookingDB
spring.datasource.username = postgres
spring.datasource.password = postgres

# for docker deployment
# spring.datasource.url = ${DB_URL:jdbc:postgresql://localhost:5432/RideBookingDB}
# spring.datasource.username = ${DB_USER:postgres}
# spring.datasource.password = ${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.show-sql = true

#smtp config
spring.mail.username=dummy@gmail.com
spring.mail.password=dummy
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secretKey = paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823